### ISSUE TITLE
pChart 2.3 -- setSerieDrawable syntax question

### ISSUE THREAD

**Issue by BudVA7ST** [bozhinov/pChart2.0-for-PHP7#33]
Hello Momchil. I love pChart 2.3 -- took me a while to figure out a few aspects of the newer syntax by tracing through the Examples files and classes. I have not been able to get "**setSerieDrawable**" working. I am using the following format:

       $pCharts->Test->myData->setSerieDrawable("Sunspots",TRUE);

Is there a new format for **setSerieDrawable** in pChart 2.3? Just wondering -- and thank you for all your work getting pChart working on PHP7+

Here's the sample code I am working with:

		 $Test = new pDraw(186,505);		 
		 $Test->setGraphArea(34,407,176,458);

		 $Test->myData->addPoints($k_index_array),"K-index");
                 $Test->myData->addPoints($flux_array_values, "Flux");
		 $Test->myData->addPoints($flux_array_dates,"Flux Dates"); 
		 $Test->myData->addPoints($sunspot_array_values,"Sunspots"); 	 
		 $Test->myData->setSerieDescription("Flux Dates","Date");
		 $Test->myData->setAbscissa("Flux Dates"); // X Axis
		 $Test->myData->setAbscissaName("Date"); // X Axis
		 $Test->myData->setSerieOnAxis("Flux",0);
		 $Test->myData->setSerieOnAxis("Sunspots",1);
		 $Test->myData->setAxisName(0,"Solar Flux"); // Y Axis Left Name
		 $Test->myData->setPalette("Sunspots",new pColor(0,102,102,100)); // Green spline
		 $Test->myData->setPalette("Flux",new pColor(99,150,189,100));  // Blue spline

		$Test->setFontProperties(["FontName"=>"pChart/fonts/Square.ttf","FontSize"=>6,"Color"=>new pColor(255)]);
		$Test->drawScale(["LabelSkip"=>1,"MinDivHeight"=>8,"Mode"=>SCALE_MODE_START0, "XMargin"=>0,"YMargin"=>0, "Floating"=>FALSE,"GridColor"=>new pColor(200),"DrawSubTicks"=>TRUE,"CycleBackground"=>FALSE]);

		$pCharts = new pCharts($Test);

		$pCharts->Test->myData->setSerieDrawable("K-index", FALSE);  // This isn't working for me

		$pCharts->drawAreaChart();
		$Test->Render("/wwv/orca_conditions.png");

**Comment by bozhinov** [comment]
Looks good to me. Will test it later today

**Comment by bozhinov** [comment]
OK do you have a working code? I tried to make this one work but could not.
from which example did you start ? example.drawAreaChart.php ?

**Comment by bozhinov** [comment]
Here is my test code:
`require_once("bootstrap.php");

use pChart\pColor;
use pChart\pDraw;
use pChart\pCharts;

$flux_array_values = [1,2,3,4,5];
$sunspot_array_values = [1,2,3,4,5];
$k_index_array = [11,12,13,14,15];

$Test = new pDraw(186,505);		 
$Test->setGraphArea(34,407,176,458);
$Test->myData->addPoints($k_index_array,"K-index");
$Test->myData->addPoints($flux_array_values, "Flux");
$Test->myData->addPoints($sunspot_array_values,"Sunspots"); 	 
$Test->myData->setAbscissaName("Date"); // X Axis
$Test->myData->setSerieOnAxis("Flux",0);
$Test->myData->setSerieOnAxis("Sunspots",1);
$Test->myData->setAxisName(0,"Solar Flux"); // Y Axis Left Name
$Test->myData->setPalette("Sunspots",new pColor(0,102,102,100)); // Green spline
$Test->myData->setPalette("Flux",new pColor(99,150,189,100));  // Blue spline

$Test->drawScale(["LabelSkip"=>1,"MinDivHeight"=>8,"Mode"=>SCALE_MODE_START0, "XMargin"=>0,"YMargin"=>0, "Floating"=>FALSE,"GridColor"=>new pColor(200),"DrawSubTicks"=>TRUE,"CycleBackground"=>FALSE]);
$Test->myData->setSerieDrawable("K-index", FALSE);  // This isn't working for me

$pCharts = new pCharts($Test);

$pCharts->drawAreaChart();
$Test->Render("orca_conditions.png");`

"K-index" is not rendered. so that part works fine.

**Comment by BudVA7ST** [comment]
Thank you-- that solved it perfectly. I was using the pCharts class (**$pCharts->Test->myData**) instead of pData class (**$Test->myData**) to try and hide the serie "K-index".

Got it working. I appreciate your time and the quick response to the question!

The working project creates a dashboard of space weather and radio propagation conditions, which can be seen on http://orcadxcc.org or as a standalone PNG at http://va7st.ca/wwv/orca_conditions.png.

**Comment by bozhinov** [comment]
Cool!

There is a sandbox though. Much easier to get you started
